### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Methuselah96** [reduxjs/redux-devtools#530]
Hey guys, I'm one of the new maintainers of Redux DevTools. Here's a list of our priorities as we become familiar with the code base and the state of this monorepo:

- [x]  1. Release latest version of all packages.
- [x]  2. Convert packages to TypeScript (in order to gain familiarity with the code base and make contributions easier).
  - [x] `react-base16-styling`
  - [x] `redux-devtools-instrument`
  - [x] `react-json-tree`
    - [x] example
  - [x] `redux-devtools`
    - [x] counter example
    - [x] todomvc example
  - [x] `react-dock`
  - [x] `redux-devtools-dock-monitor`
  - [x] `redux-devtools-log-monitor`
  - [x] `redux-devtools-serialize`
  - [x] `redux-devtools-core`
  - [x] `redux-devtools-slider-monitor`
    - [x] example
  - [x] `redux-devtools-inspector-monitor`
  - [x] `devui`
  - [x] `redux-devtools-cli`
  - [x] `d3-state-visualizer`
    - [x] example
  - [x] `redux-devtools-chart-monitor`
  - [x] `redux-devtools-test-generator`
  - [x] `map2tree`
  - [x] `d3tooltip`
  - [x] `redux-devtools-trace-monitor`
- [x]  3. Finish moving remaining packages (including `redux-devtools-extension`) to this monorepo (closing https://github.com/reduxjs/redux-devtools/issues/412).
  - [x] Move the packages
  - [x] Integrate them into Yarn workspaces
  - [x] Convert to TypeScript
- [x] 4. Fix known issues:
  - [x] The extension specific buttons that aren't included in `@redux-devtools/app`.
  - [x] The dispatcher styles are broken.
  - [x] Use new state persistence logic from `@redux-devtools/app` in the extension.
  - [x] Propagate usage of `redux-persist` to extension from app
  - [x] Fix slider monitor
- [x] 5. Test the buttons I don't use on a regular basis (e.g., import, export, lock, pin, etc.).
- [x] 6. Release new UI changes to the Redux DevTools Extension in a 3.0 release.

We'll also continue to prioritize bug fixes during this process as well. We probably won't be accepting any new features until these priorities have been completed and for the most part we're focusing on just trying to maintain Redux DevTools as-is.

**Comment by MichaelMarner** [comment]
Hey @Methuselah96 I'm the author of the [Dart/Flutter Remote Devtools](https://github.com/MichaelMarner/dart-redux-remote-devtools) package. Good to see this project getting some attention again. Once the updated versions have been published to npm I'll change our documentation to `redux-devtools-cli`.

I'd also be willing to help with some of the work required to convert to TypeScript if it's work that can be cleanly split up between devs.

Cheers!

**Comment by Methuselah96** [comment]
Hey @MichaelMarner, I've published [`redux-devtools-cli@1.0.0-2`](https://github.com/reduxjs/redux-devtools/releases/tag/redux-devtools-cli%401.0.0-2) that is mostly functional, however it's still a pre-release so I'll leave it up to you whether to start pointing to it yet or net.

Thanks for being willing to help, but converting this project to TypeScript myself has been extremely helpful in becoming familiar with the code-base and it shouldn't take me too much longer to finish converting everything over.

Let me know if there's anything else I can do for you.

Cheers!

**Comment by edoardolincetto** [comment]
Hey @Methuselah96, tasks here in the roadmap are pretty easy. I think that it could be interesting to add the `hacktoberfest` topic to the repo, just to get some help from contributors who are searching for a project!

**Comment by Methuselah96** [comment]
@edoardolincetto Thanks, but I think I'm more in favor of contributions that form organically from a developer needing a feature or a bug-fix instead of people just hunting around for open-source projects to work on.

Also, while the tasks on the roadmap might be easy, I would prefer to work on them myself since it's helping me gain familiarity with the code-base. Since I'm currently the sole maintainer of the project, I think it's important that I'm familiar with every package in this repo, and converting them to TypeScript is helping me do that.

**Comment by Methuselah96** [comment]
I am willing to add a `hacktoberfest-accepted` label to a PR if someone submits a PR that they want to get Hacktoberfest credit for. Just note that on the PR.

**Comment by jonahlibrach** [comment]
If a dispatched action causes an error, it doesn't show up in the log. 
Is it possible to make it show the action anyways?

**Comment by Methuselah96** [comment]
@jonahlibrach That sounds possible, but I'd have to look into it some more. Can you create a separate issue for that feature request?

**Comment by jonahlibrach** [comment]
@Methuselah96 https://github.com/reduxjs/redux-devtools/issues/681

**Comment by zsajjad** [comment]
@Methuselah96 #686

**Comment by JimiPedros** [comment]
Really keen to lend a hand! @Methuselah96 is there a development guide published somewhere?

**Comment by JimiPedros** [comment]
@Methuselah96 can you please add a guide for installing and running this project locally? Cheers

**Comment by Methuselah96** [comment]
@JimiPedros Yeah, I can do that. Can you create a separate issue so I remember to get to it?

**Comment by Methuselah96** [comment]
Just reviewed #861.

My plan at the moment is to release a separate v2 extension so that people can go back to that if they have issues with v3. I think after releasing that extension and removing the things that have been deprecated, v3 should be ready to go.

**Comment by Methuselah96** [comment]
v3 is released so I'm closing this. 🎉

**Comment by sshquack** [comment]
Thank you @Methuselah96 @zalmoxisus @FaberVitale for the v3 release ❤️ Love the new UI, RTK query monitor and all the little details!

<img width="1920" alt="Screenshot 000029@2x" src="https://user-images.githubusercontent.com/5678459/149202900-f3afdb16-95a5-4820-a3c3-bf5c4d331e11.png">
